name: Enquire Appointment

on:
  push:
  schedule:
    - cron: '0 13-15 * * 1-5'  # Runs hourly from 9pm to 11pm HKT, Monday through Friday.
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run hkpr.sh
      run: |
        chmod +x ./hkpr.sh
        ./hkpr.sh "${{ secrets.REFERENCE }}" "${{ secrets.BIRTHDAY }}" "${{ secrets.SERVER }}"

    - if: ${{ failure() }}
      name: Disable workflow
      run: gh workflow disable check.yml
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
